### ISSUE TITLE
Question regarding config.py configuration

### ISSUE THREAD

**Issue by bluestone12** [j178/spotlight#2]
Hi j178,

Thank you so much for developing this tool. I am new to Weibo API and I'm trying to start with your code, and encountered some questions. Thank you in advance for your help with these.

1. what is the WEIBO_TOKEN_FILE and SINCE_ID_FILE in config.py? is this something the user needs to define themselves or a feature of json (I couldn't find them anywhere)

2. what is the use of the SINCE_ID_FILE in watchyou.py? It seems that it's getting information about the target user, but would this not be possible by directly using the user's uid?

I realized that these are probably very stupid questions, and I really appreciate if you could help a rookie out here. Thank you again!

**Comment by j178** [comment]
Hi,
1. WEIBO_TOKEN_FILE and SINCE_ID_FILE are both local cache files, WEIBO_TOKEN_FILE is for authorization token after you get it from Weibo, SINCE_ID_FILE is for the message id you fetched last time.
2. SINCE_ID_FILE is the record of message id you fetched from weibo, if you dont specify a since_id, you just get a bunch of newest statuses of your target user.

BTW, this project is no longer recommend, weibo api has changed a lot these days, you should better look for some constantly updated project instead.
